# travis-ci 
os: linux
sudo: required
dist: trusty
language: generic

before_install:
    - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
    - sudo apt-get -qq update
    - sudo apt-get -t trusty-backports install shellcheck
    - sudo pip3 install bashate

script:
- /bin/bash tests/shellcheck.sh
- /bin/bash tests/bashate.sh
